import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./Components/Footer/Footer";
import Navbar from "./Components/Header/Navbar";
import Provider from "./Components/Provider/AuthenticationProvider/Provider";
import StoreProvider from "./Components/Provider/Store/StoreProvider";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <Provider>
            <Navbar />
            <Toaster />
            {children}
            <Footer />
          </Provider>
        </StoreProvider>
      </body>
    </html>
  );
}
